Transform: AWS::Serverless-2016-10-31

Parameters:
  SteamApiKey:
    Type: AWS::SSM::Parameter::Value<String>
  CorsOrigins:
    Type: CommaDelimitedList
  CdnHostname:
    Type: String
    Default: https://cdn.steamcheetos.com
#  CdnCertificateArn:
#    Type: String
#    ARN of the CDN's ACM certificate
  ServerHost:
    Type: String
  KeyAdminUsername:
    Type: String
    Description: IAM name of user that will admin the key

Globals:
  Function:
    Runtime: java11
    MemorySize: 2048
    Environment:
      Variables:
        AUTH_KEY_ID: !Ref EncryptionKey
        GAMES_TABLE: !Ref Games
        ACHIEVEMENTS_TABLE: !Ref Achievements
        STEAM_API_KEY: !Ref SteamApiKey
        CORS_ORIGINS: !Join [ ',', !Ref CorsOrigins ]
        SERVER_HOST: !Ref ServerHost
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1  # Optimize AOT compilation for cold-start time
        CDN_HOST: !Ref CdnHostname

Resources:
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowCredentials: true
        AllowHeaders: [ Authorization ]
        AllowMethods: [ GET, POST ]
        AllowOrigins: !Ref CorsOrigins
        ExposeHeaders: [ '*' ]
      DisableExecuteApiEndpoint: true

  ApiHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Timeout: 10
      Handler: io.andrewohara.cheetosbros.ApiLambdaHandler
#      Tracing: Active
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Games
        - DynamoDBCrudPolicy:
            TableName: !Ref Achievements
        - KMSEncryptPolicy:
            KeyId: !Ref EncryptionKey
        - KMSDecryptPolicy:
            KeyId: !Ref EncryptionKey
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  EncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:user/${KeyAdminUsername}
            Action:
              - kms:*
            Resource: '*'
      KeySpec: RSA_2048
      KeyUsage: ENCRYPT_DECRYPT

  Games:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE

  Achievements:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: libraryId
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: libraryId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE

#  SteamCdn:
#    Type: AWS::CloudFront::Distribution
#    Properties:
#      DistributionConfig:
#        Aliases: [ !Ref CdnHostname ]
#        DefaultCacheBehavior:
#          AllowedMethods: [ GET, HEAD, OPTIONS ]
#          CachedMethods: [ GET, HEAD, OPTIONS ]
#          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
#          PathPattern: '*'
#          ViewerProtocolPolicy: redirect-to-https
#        Enabled: true
#        Origins:
#          - Id: steam-cdn
#            DomainName: cdn.akamai.steamstatic.com
#            CustomOriginConfig:
#              OriginProtocolPolicy: https-only
#        PriceClass: PriceClass_100
#        ViewerCertificate:
#          AcmCertificateArn: !Ref CdnCertificateArn
#          MinimumProtocolVersion: TLSv1.2_2021
#          SslSupportMethod: sni-only
