Transform: AWS::Serverless-2016-10-31

Parameters:
  PrivatePemSsmName:
    Type: String
  PublicPemSsmName:
    Type: String
  SteamApiKeySsmName:
    Type: String
  FrontendHost:
    Type: String

Resources:
  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowCredentials: true
        AllowHeaders: [ Authorization ]
        AllowMethods: [ GET, POST ]
        AllowOrigins: [ !Ref FrontendHost ]
        ExposeHeaders: [ '*' ]
      DisableExecuteApiEndpoint: true


  ApiHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: java11
      Timeout: 10
      Handler: io.andrewohara.cheetosbros.ApiLambdaHandler
      MemorySize: 1024
      Environment:
        Variables:
          GAMES_TABLE: !Ref Games
          ACHIEVEMENTS_TABLE: !Ref Achievements
          ACHIEVEMENT_STATUS_TABLE: !Ref AchievementStatus
          USERS_TABLE: !Ref Users
          SOCIAL_LINK_TABLE: !Ref SocialLinks
          LIBRARY_TABLE: !Ref GameLibrary
          STEAM_API_KEY_NAME: !Ref SteamApiKeySsmName
          PRIVATE_PEM_NAME: !Ref PrivatePemSsmName
          PUBLIC_PEM_NAME: !Ref PublicPemSsmName
          FRONTEND_HOST: !Ref FrontendHost
          PEM_ISSUER: !Ref AWS::StackName
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
      Policies:
        - DynamoDBCrudPolicy:
           TableName: !Ref Users
        - DynamoDBCrudPolicy:
           TableName: !Ref Games
        - DynamoDBCrudPolicy:
           TableName: !Ref Achievements
        - DynamoDBCrudPolicy:
           TableName: !Ref GameLibrary
        - DynamoDBCrudPolicy:
           TableName: !Ref AchievementStatus
        - DynamoDBCrudPolicy:
            TableName: !Ref SocialLinks
        - Version: "2012-10-17"
          Statement:
            - Sid: "ssm"
              Effect: "Allow"
              Action:
                - "ssm:GetParameters"
                - "ssm:GetParameter"
                - "ssm:GetParametersByPath"
              Resource:
                - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${PrivatePemSsmName}
                - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${PublicPemSsmName}
                - !Sub arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${SteamApiKeySsmName}

  Users:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  Games:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: uuid
          KeyType: HASH

  Achievements:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: gameUuid
          AttributeType: S
        - AttributeName: achievementId
          AttributeType: S
      KeySchema:
        - AttributeName: gameUuid
          KeyType: HASH
        - AttributeName: achievementId
          KeyType: RANGE

  GameLibrary:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: playerUuid
          AttributeType: S
        - AttributeName: gameId
          AttributeType: S
      KeySchema:
        - AttributeName: playerUuid
          KeyType: HASH
        - AttributeName: gameId
          KeyType: RANGE

  AchievementStatus:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: playerAndGameId
          AttributeType: S
        - AttributeName: achievementId
          AttributeType: S
      KeySchema:
        - AttributeName: playerAndGameId
          KeyType: HASH
        - AttributeName: achievementId
          KeyType: RANGE

  SocialLinks:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: playerUuid
          AttributeType: S
      KeySchema:
        - AttributeName: playerUuid
          KeyType: HASH
